title: "#幻塔管理"
subTitle: "Yunzai-Bot & TOP-Plugin"

content:
- group: "主管理"
  list:
    - icon: 55
      title: "#幻塔配置更改+配置名*数值"
      desc: "#幻塔配置更改撤回时间*30"
    - icon: 55
      title: "#幻塔更新"
      desc: "更新TOP插件"
